highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: FÃ¡bio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Greig Strafford's Resume
name: Greig Strafford
email: greig@strafford.co.nz
email_full: mailto:greig@strafford.co.nz
website: strafford.co.nz
website_full: https://strafford.co.nz
github: straff2002
twitter: straff2002
tel: +64 224 758650
tel_full: tel:+64224758650
google_maps: 'https://www.google.co.uk/maps/place/Auckland'
#address: 44 Perth Street
#postcode: EH3 5BL
#city: Edinburgh
country: New Zealand
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
